### PR TITLE
feat: convert to typescript

### PR DESCRIPTION
**Pull request by ethanve**

### CODE REVIEW

**Comment by ethanve** [comment]
Can someone explain the error `error  Definition for rule 'react/jsx-filename-extension' was not found  react/jsx-filename-extension`?

**Comment by jquense** [comment]
@ethanve the error is due to: https://github.com/4Catalyzer/javascript/blob/master/packages/eslint-config-4catalyzer-typescript/rules.js#L2-L7 Sometimes the config find the react plugin, even tho the plugin is not enabled in the config. It should b e the case that it isn't installed if it's not used but…node_modules gonna be node_modules. Just add the react plugin to the eslint config to fix it

**Comment by ethanve** [comment]
Done. removed the react eslint configs. Also deleted the example. Will redo it with relay-modern https://github.com/relayjs/relay-examples

**Comment by ethanve** [comment]
Why does this bot not follow our package.json!?

**Pull request merged**
