### PR TITLE
BREAKING CHANGE: socket io v3 update

### PR DESCRIPTION
**Pull request by c0state**
Oops, actually, semantic release inspects npm versions it looks like. Need this PR to push the real 2.0.0 release.

Also, can we archive 1.2.1? That version is borked...

### CODE REVIEW

**Comment by c0state** [comment]
> we shouldn't be bumping versions manually, the release scripts do that automatically and will probably break if the version doesn't change from their perspective
> 
> for triggering a manual release add a `MANUAL_RELEASES.md` that just contains the line `number of manual releases: 0` then increment the number as the change

Agreed, that's a better way--changed. This should work now correct? Also, can you unpublish `1.2.1`? (or should we--I think so?)

**Comment by jquense** [comment]
i can try and un publish it, may be that too much time has passed

**Comment by c0state** [comment]
This can be merged right? Unsure of convention here--was waiting on explicit approval, though I think this looks fine...

**Pull request merged**
